"""Add task count tables

Revision ID: 999ffd6ade6f
Revises: c0cafd7ca22f
Create Date: 2025-03-18 01:08:16.709984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999ffd6ade6f'
down_revision: Union[str, None] = 'c0cafd7ca22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_task_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_task_count_id'), 'deleted_task_count', ['id'], unique=False)
    op.create_table('updated_task_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_updated_task_count_id'), 'updated_task_count', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_updated_task_count_id'), table_name='updated_task_count')
    op.drop_table('updated_task_count')
    op.drop_index(op.f('ix_deleted_task_count_id'), table_name='deleted_task_count')
    op.drop_table('deleted_task_count')
    # ### end Alembic commands ###
